### ISSUE TITLE
Texas Solar Pad 11 and Demo missing

### ISSUE THREAD

**Issue by susanbruno** [MTStrot/Solar-Overlay#2]
Texas Solar 1 only showing 10 power stations instead of 11 power stations and the DEMO does not show up on the new SCADA at all.

**Comment by MTStrot** [comment]
Pad 11 has been added. DEMO will be added soon.

**Comment by MTStrot** [comment]
![image](https://user-images.githubusercontent.com/33523612/72300091-c7677e00-3630-11ea-9d2a-336699bd9c5d.png)

Demo pad has been added
