### ISSUE TITLE
Taylorsville

### ISSUE THREAD

**Issue by PASisson** [MTStrot/Solar-Overlay#3]
VT Solar SCADA is showing Inverters 1 & 2 in 1 icon and you have to scroll to see the 2nd inverter both need to be displayed side by side to be visible at all times.
Meters in Grantek SCADA read in KW - Meters in New VT SCADA read in MW

**Comment by MTStrot** [comment]
For consistency, all meters should read MW in the new overlay.  I did this because for larger sites, meters would show values of 100000+ kW, which would be difficult to display/read.

Inverter scrolling issue has been fixed.
